name: Setup Cuttlefish
description: Download, install, and start the Cuttlefish Android emulator

inputs:
  cuttlefish-version:
    description: 'Cuttlefish version tag (e.g., v1.32.0)'
    required: false
    default: 'v1.32.0'
  android-branch:
    description: 'Android branch to download (e.g., aosp-android-latest-release)'
    required: false
    default: 'aosp-android-latest-release'
  android-device:
    description: 'Android device type (e.g., aosp_cf_x86_64_only_phone)'
    required: false
    default: 'aosp_cf_x86_64_only_phone'
  memory-mb:
    description: 'Memory allocation for the emulator in MB'
    required: false
    default: '8192'
  cpus:
    description: 'Number of CPUs to allocate (default: all available)'
    required: false
    default: '0'

outputs:
  build-id:
    description: 'Android build ID that was downloaded'
    value: ${{ steps.build-id.outputs.BUILD_ID }}

runs:
  using: composite
  steps:
    - name: Add Android SDK to PATH
      shell: bash
      run: echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

    - name: Cache Cuttlefish packages
      id: cache-cf-packages
      uses: actions/cache@v4
      with:
        path: ~/cuttlefish-packages
        key: cf-packages-${{ inputs.cuttlefish-version }}

    - name: Download Cuttlefish packages
      if: steps.cache-cf-packages.outputs.cache-hit != 'true'
      shell: bash
      run: |
        RUN_ID=$(gh run list --repo google/android-cuttlefish --workflow .github/workflows/main.yml \
          --json databaseId,headBranch,status \
          --jq ".[] | select(.headBranch == \"${{ inputs.cuttlefish-version }}\") | select(.status == \"completed\") | .databaseId" \
          | head -1)
        
        mkdir -p ~/cuttlefish-packages
        cd ~/cuttlefish-packages
        gh run download $RUN_ID --repo google/android-cuttlefish --name debs_amd64
        tar -xf debs_amd64.tar
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Install Cuttlefish
      shell: bash
      run: |
        sudo apt-get update
        sudo dpkg -i ~/cuttlefish-packages/cuttlefish-base_*_*64.deb || sudo apt-get install -f -y
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules && sudo udevadm trigger
        sudo usermod -aG kvm,cvdnetwork,render $USER

    - name: Get Android build ID
      id: build-id
      shell: bash
      run: |
        TARGET="${{ inputs.android-device }}-userdebug"
        BUILD_ID=$(curl -sL "https://ci.android.com/builds/branches/${{ inputs.android-branch }}/status.json" | \
          jq -r ".targets[] | select(.name == \"$TARGET\") | .last_known_good_build")
        echo "BUILD_ID=$BUILD_ID" >> $GITHUB_OUTPUT
        echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
        echo "CF_HOME=$HOME/cuttlefish" >> $GITHUB_ENV

    - name: Cache Android images
      id: cache-images
      uses: actions/cache@v4
      with:
        path: ~/cuttlefish-downloads
        key: android-images-${{ steps.build-id.outputs.BUILD_ID }}

    - name: Download Android images
      if: steps.cache-images.outputs.cache-hit != 'true'
      shell: bash
      run: |
        TARGET="${{ inputs.android-device }}-userdebug"
        BASE_URL="https://ci.android.com/builds/submitted/${BUILD_ID}/${TARGET}/latest/raw"
        
        mkdir -p ~/cuttlefish-downloads
        curl -L "${BASE_URL}/${{ inputs.android-device }}-img-${BUILD_ID}.zip" -o ~/cuttlefish-downloads/system-img.zip
        curl -L "${BASE_URL}/cvd-host_package.tar.gz" -o ~/cuttlefish-downloads/host-package.tar.gz

    - name: Setup Cuttlefish
      shell: bash
      run: |
        mkdir -p $HOME/cuttlefish
        tar xzf ~/cuttlefish-downloads/host-package.tar.gz -C $HOME/cuttlefish
        unzip -q ~/cuttlefish-downloads/system-img.zip -d $HOME/cuttlefish

    - name: Start emulator
      shell: bash
      run: |
        CPUS="${{ inputs.cpus }}"
        if [ "$CPUS" = "0" ]; then
          CPUS=$(nproc)
        fi
        
        sg kvm -c "sg cvdnetwork -c 'HOME=$HOME/cuttlefish $HOME/cuttlefish/bin/launch_cvd \
          -daemon -enable_sandbox=false -memory_mb=${{ inputs.memory-mb }} -cpus=$CPUS -report_anonymous_usage_stats=n'"
        
        adb wait-for-device
        
        timeout 600 bash -c 'until [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d "\r")" = "1" ]; do sleep 5; done'
        
        # Unlock the screen
        adb shell input keyevent 82
        sleep 2
        adb shell input swipe 540 1800 540 400
        sleep 1
        
        echo "Emulator ready!"
